linux:
	g++ -std=c++17 -O2 -pipe -s ayt-player-cli.cpp -o ayt-player -lSDL2

windows:
	g++ -std=c++17 -O2 -pipe -s \
	ayt-player-cli.cpp -o ayt-player.exe \
	-lmingw32 -lSDL2main -lSDL2 \
	-static-libgcc -static-libstdc++
