;;============================================================================================================================================ 
;;              _____  __     _____  _____  _____    _____  _____  _____  _____    _____  __     _____  __ __  _____  _____
;;             |  |  ||  |   |_   _|| __  ||  _  |  |   __||  _  ||   __||_   _|  |  _  ||  |   |  _  ||  |  ||   __|| __  |
;;             |  |  ||  |__   | |  |    -||     |  |   __||     ||__   |  | |    |   __||  |__ |     ||_   _||   __||    -|
;;             |_____||_____|  |_|  |__|__||__|__|  |__|   |__|__||_____|  |_|    |__|   |_____||__|__|  |_|  |_____||__|__|
;;
;;                                                                                            ,,
;;                                 db      `YMM'   `MM'    MMP""MM""YMM                      *MM
;;                                ;MM:       VMA   ,V      P'   MM   `7                       MM
;;                               ,V^MM.       VMA ,V            MM      `7MM  `7MM  `7Mb,od8  MM,dMMb.   ,pW"Wq.
;;                              ,M  `MM        VMMP             MM        MM    MM    MM' "'  MM    `Mb 6W'   `Wb
;;                              AbmmmqMA        MM              MM        MM    MM    MM      MM     M8 8M     M8
;;                             A'     VML       MM              MM        MM    MM    MM      MM.   ,M9 YA.   ,A9
;;                           .AMA.   .AMMA.   .JMML.          .JMML.      `Mbod"YML..JMML.    P^YbmdP'   `Ybmd9'
;;
;;
;;============================================================================================================================================
;; 
;;                                                              _ (`-.         ('-.
;;                                                             ( (OO  )       ( OO ).-.
;;                                            ,----.          _.`     \       / . --. /
;;                                           '  .-./-')      (__...--''       | \-.  \
;;                                           |  |_( O- )      |  /  | |     .-'-'  |  |
;;                                           |  | .--, \      |  |_.' |      \| |_.'  |
;;                                          (|  | '. (_/      |  .___.'       |  .-.  |
;;                                           |  '--'  |  .-.  |  |      .-.   |  | |  | .-.
;;                                            `------'   `-'  `--'      `-'   `--' `--' `-'
;;
;;
;;                                                         .-') _      .-')                   .-')     .-') _       ('-.    _   .-')
;;                                                        ( OO ) )    ( OO ).                ( OO ).  (  OO) )    _(  OO)  ( '.( OO )_
;;   ,--.       .-'),-----.   ,----.      .-'),-----. ,--./ ,--,'    (_)---\_)   ,--.   ,--.(_)---\_) /     '._  (,------.  ,--.   ,--.)
;;   |  |.-')  ( OO'  .-.  ' '  .-./-')  ( OO'  .-.  '|   \ |  |\    /    _ |     \  `.'  / /    _ |  |'--...__)  |  .---'  |   `.'   |
;;   |  | OO ) /   |  | |  | |  |_( O- ) /   |  | |  ||    \|  | )   \  :` `.   .-')     /  \  :` `.  '--.  .--'  |  |      |         |
;;   |  |`-' | \_) |  |\|  | |  | .--, \ \_) |  |\|  ||  .     |/     '..`''.) (OO  \   /    '..`''.)    |  |    (|  '--.   |  |'.'|  |
;;   |  '---.'   \ |  | |  |(|  | '. (_/   \ |  | |  ||  |\    |     .-._)   \  |   /  /\_  .-._)   \    |  |     |  .--'   |  |   |  |
;;   |      |     `'  '-'  ' |  '--'  |     `'  '-'  '|  | \   |     \       /  `-./  /.__) \       /    |  |     |  `---.  |  |   |  |
;;   `------'       `-----'   `------'        `-----' `--'  `--'      `-----'     `--'       `-----'     `--'     `------'  `--'   `--'
;;
;;============================================================================================================================================
;; AY Turbo Player for Enterprise - Dave Chipset 
;; AYT Player is generated by AYT Builder
;; CONSTANT CPU Execution, NO buffer, NO unpacking, LOOP everywhere, NO Address limitations,  NO ROM Flipping, TINY Size
;;
;; 18/03/2026
;; Credits 
;; YM to AYT Org converter       : Tronic (GPA)
;; YM to Dave Converter	         : Longshot (Logon System)
;; EP128 AYT Z80A player/Builder : Longshot (Logon System) (Serge Querne @ logon.system@free.fr)
;;============================================================================================================================================
;; The sound processor in the ENTERPRISE computer is called Dave (named after its designer, Dave Woodfield). 
;; In some respects, it is quite similar to the AY-3-8912 (for example, a standard 3-channel, 12-bit square wave from 30 Hz to 125 kHz). 
;; However, it is capable of applying distortion to these frequencies using polynomial counters of varying resolutions, processing a high-pass filter 
;; based on another channel, and handling a ring modulator (a form of signal fusion). 
;; Unlike the AY-3-891x, the noise channel is completely independent of the other channels and has its own volume control. 
;; It can drive two speakers per channel and for the noise channel, resulting in a total of eight amplitudes with a 6-bit resolution (compared to four for the AY). 
;; Finally, it is possible to switch the square wave signal from channel 0 to a 6-bit D/A output. 
;; These features, combined with extremely simple and fast access (compared to what exists on the AY for other platforms, and especially the CPC), 
;; make this processor a marvel considering its age.
;;
;; Despite these features, two points are problematic when it comes to transferring data from an AY-3-8912 (or compatible). 
;; The white noise channel is limited to a sound with an "autonomous" frequency of 31.25 kHz or a sound whose frequency is aligned with that of one 
;; of the three tone channels (but on which the size of the polynomial counters, etc., can still be adjusted). 
;; The consequence of this independence is the absence of a mixing register (like R7 on the AY, which merges the noise with one or more channels). 
;; Muting a channel therefore requires setting its volume to 0. 
;; But the most annoying point, in order to "mimic" the AY, is the absence of management of a predefined hardware envelope (attack + cyclic values) whose 
;; periodicity can be parameterized.
;;
;; I won't dwell on the unfortunate history of the Enterprise. 
;; This history led to frequent adaptations of AY music, without any real consideration for its actual capabilities. 
;; It's the same process as the ports of ZX games to the CPC or Enterprise, which didn't truly take advantage of the target machines' capabilities. 
;; Simulating the noise channel can prove problematic if you want to closely replicate the AY, because the latter allows you to define 32 different frequencies, 
;; whereas beyond polynomial counters, Dave only has one frequency, or must "match" it to that of a channel... Solutions exist, but none are ideal. 
;; Furthermore, many AY music tracks utilize hardware amplitude envelope management, which can provide, for example, a form of "smoothing" between notes.
;;
;; Software simulation of these envelopes can be very CPU-intensive. 
;; Several solutions exist, depending on the desired precision. 
;; It's possible to use the Dave interrupt at 1 kHz (20 interrupts per frame), but this requires software smoothing (via a slope adder) to handle the amplitude 
;; updates for the channel(s) involved. It's also possible to use Nick (the sound processor) to generate interrupts every two lines, but this comes at the cost 
;; of a fairly large Line Parameter Table (LPT).
;;
;; Consequently, I converted and adapted the AYT data (without altering its structure) to allow for the rapid processing of YM data intended for AY-3-891x 
;; and converted to AYT without envelope management. One might think the impact would be significant on music that relies almost constantly on these hardware 
;; envelopes, but the difference isn't bad in itself (though I'm not a musician). Based on this, we can consider processing "purely" Dave music using unused 
;; functions via certain trackers that handle them (like Furnace). 
;; This also guarantees a very short execution time in fixed time (provided, of course, that the player doesn't run in video RAM).
;;
;; I've also created a version that handles hardware envelopes via the 1kHz interrupt, but I haven't "finalized" it since I haven't created the builder for 
;; the player and haven't yet automated certain variables (number of bytes per pattern, for example). 
;; The CPU usage of these interrupts, which I've tried to minimize as much as possible, isn't fixed time, since these interrupts are asynchronous with Nick's Vsync.
;; If there is demand, I will finalize this work.:-)
;;
;;============================================================================================================================================
;; Performances
;; ------------
;; Mono Mode
;; ------------
;; Option PlayerAccessByJP equ 0	; CALL player
;;     10 registers : 611 Ts (call included) / Player Size: 111 bytes
;;     09 registers : 572 Ts (call included) / Player Size: 106 bytes 
;;     08 registers : 533 Ts (call included) / Player Size: 101 bytes 
;;     07 registers : 494 Ts (call included) / Player Size: 96 bytes 
;;     Size of Ayt_Builder : 309 bytes
;; Option PlayerAccessByJP equ 1	; JP player
;;     10 registers : 574 Ts (jp included) / Player Size: 106 bytes 
;;     09 registers : 535 Ts (jp included) / Player Size: 101 bytes 
;;     08 registers : 496 Ts (jp included) / Player Size: 96 bytes 
;;     07 registers : 457 Ts (jp included) / Player Size: 91 bytes 
;;     Size of Ayt_Builder : 294 bytes
;; ------------
;; Stereo Mode
;; ------------
;; Cpu : Add 44 Ts if Stereo Option is active (Max:4 volume (11x4))
;; Size: Add 8 bytes if Stereo Option is active (Max:4 volume (2x4))
;;----------------------------------------------------------------------------------------------------------------------------------------------
;; Init Dave Reg routine
;;------------------------------------------------------
;; Size of routine : 16 bytes
;; The Dave register initialization routine is created if constant registers require prior initialization. 
;; User can define whether to specify a 16-byte area for this single-use initialization, or whether to let the builder define the address after the player. 
;; In all cases, builder returns the address where the initialization routine was created. 
;; Note that if the initialization routine is not necessary, it will contain a single ret.
;;--------------------------------------------------------------------------
;; Notes :
;; Ayt Builder can be removed once music player built & music data initialized.
;; (i.e. you can use the player and the data file completely independently of the Ayt builder)
;; Performance is given for 10 to 7 non-constant registers, but the player can handle a variable number of constant registers. 
;; For example, if a song uses only two channels, then performance will be better.
;;============================================================================================================================================
;; Technical information about AYT Format
;; --------------------------------------
;; Ayt_Start
;; struct AYT_Header
;; { 
;;  uint8_t Ayt_Version      	; version aaaabbbb >> a.b
;;  uint16_t Ayt_ActiveRegs     ; active reg (bit 15:reg 0...bit 2:reg 13) 1=active 0:inactive
;;  uint8_t Ayt_PatternSize  	; Pattern size 1..255
;;  uint16_t Ayt_FirstSeqMarker ; Offset from Ayt_Start for Seq Ptr on patterns
;;  uint16_t Ayt_LoopSeqMarker 	; Offset from Ayt_Start for Loop Seq Ptr 
;;  uint16_t Ayt_ListInit	; Offset from Ayt_Start for Init of ay reg (*)
;;  uint16_t Ayt_NbPatternPtr  	; Nb of pattern ptr seq for music (NbSeq x NbReg)
;;  uint8_t  Ayt_PlatformFreq	; Platform (b0..4) & Frequency (b5..7) (see table) (**)
;;  uint8_t  Ayt_Reserved	; Reserved for future version (=0)
;; }
;; Start of Patterns
;;
;; (*)
;; struct Ay_Init 
;; {
;;  uint8_t Ayt_Reg		; No reg (0 to 13) 
;;  uint8_t Ayt_Val
;; } x N register to initialize
;; Last byte=#ff
;;
;; (**) 
;; bit 4..0 00000 AMSTRAD CPC (1 000 000 hz)
;;          00001 ORIC        (1 000 000 hz)
;;          00010 ZXUNO       (1 750 000 hz)
;;          00011 PENTAGON    (1 750 000 hz)
;;          00100 TIMEXTS2068 (1 764 000 hz)
;;          00101 ZX128       (1 773 450 hz)
;;          00110 MSX         (1 789 772 hz)
;;          00111 ATARI ST    (2 000 000 hz)
;;          01000 VG5000      (1 000 000 hz) (Ext card VG5210)
;;          01001 ENTERPRISE  (2 000 000 hz) (Dave tone base freq)
;;          11111 UNKNOWN  
;;
;; bit 7..5 000 50 hz
;;          001 25 hz
;;          010 60 hz
;;          011 30 hz
;;          111 UNKNOWN
;;
;; Start of Sequences of ptr on Pattern by Reg  
;;
;; A "Last Sequence" is generated after the last seq of AYT file.
;; Last sequence consists of Ayt_NbRegs pointers on 2 special 'pattern' bytes
;; This is done :
;; - to mute the music at end of play (some ym music don't do the job sometimes)
;; - to give end music status to player
;; Detail of the last sequence : Ayt_NbReg x WordPointer + 2 'pattern' bytes
;;               9 identical ptr on pattern 1 b with 0
;;               1 ptr for vol channel 1 (#A8) on pattern 1b with #80 
;;			bit 7 >> if 1 : Music End
;;============================================================================================================================================
;;
;;----------------------------------------------------------------------------------------------------------------------------------------------
;; Compilation option
;;----------------------------------------------------------------------------------------------------------------------------------------------
;;
;; PlayerAccessByJP option
;;
;; In most situations, the player can be called with the Z80A "call" instruction. 
;; The player uses the stack as a fast data pointer. 
;; It therefore saves the SP register and returns it when it finishes its work.
;; However, in a few exceptional situations, you might need to modify SP in your main code (to also use it as a fast pointer), 
;; and it would therefore not be useful for the player to waste time saving it. 
;; This, however, requires calling the player differently. 
;; The "PlayerAccessByJP" compile option, when set to 1, allows you to assemble "Ayt_Builder" to handle access to the player via the Z80A "JP" instruction. 
;; It is then necessary to specify the return address in the input parameters of "Ayt_Builder" (in the HL register). 
;; Access to the player is then done with a "JP Player" instead of a "CALL Player", and the player will then return to your main program with a JP on the 
;; address you provided in HL to the "Ayt_builder".
;; In terms of technical figures, this option allows you to reduce the size of the built player by 5 bytes, and to save 37 Ts of CPU 
;; (since the SP backup is no longer ensured) 
;; Also I draw your attention to the following point: this call method implies determining in advance the return address of the "player". 
;; In development, if the return address is a label that varies, this forces the presence of the Ayt_Builder in memory at each compilation.
;;
;;
PlayerAccessByJP	equ 0		; If 1, requires you to take into account that SP has been wildly modified
;;----------------------------------------------------------------------------------------------------------------------------------------------
;;
;; PlayerStereo option
;; The Enterprise has 3 tone channels and 1 noise channel. 
;; Each of these channels has 2 amplitude registers (6 in total), allowing independent volume control for left and right speakers. 
;; Internally, the machine has one built-in speaker. Stereo sound is possible with external speakers. 
;; Music from the YM-2149 or AY-3-8912 is considered mono; therefore, unless the music is capable of handling two speakers, 
;; the player will only send the volume to one speaker. However, it is possible to force both speakers to be sent by setting this option to 1. 
;; In this case, the player will consume a maximum of 4 x 11 = 44 TS additional resources.
;;
PlayerStereo		equ 0		; If 1, Output is managed on Right Speaker (external device) (Until 4 additional OUT(#nn),A )
;-----------------------------------------------------------------------------------------------------------------------------------------------
AYT_OFS_Version		equ 0	;; Not yet used (hey it's the 1st version)
AYT_OFS_ActiveRegs	equ 1	;; active reg (bit 0:reg 0...bit 13:reg 13) 1=active (only r12 off is managed in v1)
AYT_OFS_PatternSize	equ 3	;; Pattern size in bytes from 1 to 255
AYT_OFS_FirstSeq	equ 4	;; Offset on first Seq Ptr for start
AYT_OFS_LoopSeq		equ 6	;; Offset on Seq Ptr for loop
AYT_OFS_ListInit	equ 8	;; Offset on Ay Init List
AYT_OFS_NbPatternPtr	equ 10	;; Nb of pattern ptr seq for music (NbSeq x NbReg)
AYT_OFS_PlatformFreq	equ 12  ;; Platform & Freq of play (see table)
AYT_OFS_Reserved	equ 13	;; Rhaaaaaaa
AYT_SIZE_HEADER		equ 14	;; Header size to find first pattern

	ifnot PlayerAccessByJP
		OFS_B1_PtrSaveSP	equ Ayt_PtrSaveSP-Ayt_Player_B1a_Start
		OFS_B3_Ayt_ReloadSP	equ Ayt_ReloadSP-Ayt_Player_B3_Start	
	endif
OFS_B1a_FirstSeq	equ Ayt_FirstSeq-Ayt_Player_B1a_Start 
 
OFS_B3_SeqPatPtr_Upd	equ Ayt_SeqPatternPtr_Upd-Ayt_Player_B3_Start		
OFS_B3_PatCountPtr1	equ Ayt_PatCountPtr1-Ayt_Player_B3_Start
OFS_B3_PatCountPtr2	equ Ayt_PatCountPtr2-Ayt_Player_B3_Start			
OFS_B3_MusicCnt		equ Ayt_MusicCnt-Ayt_Player_B3_Start
OFS_B3_MusicCntPtr	equ Ayt_MusicCntPtr-Ayt_Player_B3_Start
OFS_B3_Ayt_NotLastSeq	equ Ayt_NotLastSeq-Ayt_Player_B3_Start

AYT_B2_SIZE		equ Ayt_Player_B2_End-Ayt_Player_B2_Start	
AYT_B3_SIZE		equ Ayt_Player_B3_End-Ayt_Player_B3_Start
AYT_B4_SIZE		equ Ayt_Player_B4_End-Ayt_Player_B4_Start

_AYT_BUILDER_SIZE	equ AYT_Builder_End-AYT_Builder_Start
;-----------------------------------------------------------------------------------------------------------------------------------------------

;;++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
;; Ayt Builder
;;
;;	in :	ix=address AYT file
;;		de=msb address Player
;;		a=nbloop expected
;;		hl (optional)=return address of player (only if Builder is compiled with PlayerAccessByJP equ 1)
;;	out : 
;;              hl=ptr on the init routine to call 1 time before to use player address.
;;		de=ptr on the first free byte after the player
;;
;;++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
AYT_Builder_Start
		di
		ld (Ayt_MusicCnt),a		; Nb of loop for music
		ld a,(ix+AYT_OFS_PatternSize)
		ld (Ayt_PatternSize),a		; Set Pattern Size
	if PlayerAccessByJP
		ld (Ayt_ExitPtr01),hl		; Set Main code return address
	else
		push de				; save ptr on first bloc for SP reload
	endif	
		;;-------------------------------------------------------------------------------------------------------------------------------
		;; In AYT file , relocate sequence list ptr on rxx data. (absolute address)
		;; In >> ix=Ptr on AYT File
		;; Out >> de not modified
		;;-------------------------------------------------------------------------------------------------------------------------------
		push de				; save ptr for player
		push ix
		pop bc				; bc=Ptr on start of AYT file
		; 
		ld l,(ix+AYT_OFS_ListInit)	; Offset on Init List 
		ld h,(ix+AYT_OFS_ListInit+1)
		add hl,bc			; Ptr on Ay Init List 
		ld (Ayt_PtrInitList),hl		; In Block 4 if created
		ld a,(hl)			; If empty list , just need a Ret in init code
		ld (Ayt_InitCreate),a

		;
		ld l,(ix+AYT_OFS_LoopSeq)	; Offset of Loop Sequence
		ld h,(ix+AYT_OFS_LoopSeq+1)
		add hl,bc
		ld (Ayt_LoopSeq),hl		; Set Loop Sequence
		; 
		ld l,(ix+AYT_OFS_FirstSeq)	; read offset of first seq from start
		ld h,(ix+AYT_OFS_FirstSeq+1)
		add hl,bc			; Ptr on first sequence
		ld (Ayt_FirstSeq),hl
		push hl
		pop iy				; IY ptr on first sequence of pattern ptr by reg
		;
		ld hl,AYT_SIZE_HEADER
		add hl,bc
		ld b,h
		ld c,l
		;
		ld e,(ix+AYT_OFS_NbPatternPtr)
		ld d,(ix+AYT_OFS_NbPatternPtr+1); Nb of Pattern Ptr in all Sequence of AYT file
Ayt_PtrFix_b1
		ld l,(iy+0)
		ld h,(iy+1)			; Read Offset Seq
		add hl,bc			; Absolute Address for Seq Ptr on Rxx
		ld (iy+0),l
		ld (iy+1),h
		inc iy				; Next Seq Ptr rxx+1
		inc iy
		dec de
		ld a,d
		or e
		jr nz,Ayt_PtrFix_b1		; loop all sequence
		pop de				; Ptr for player

		;;-------------------------------------------------------------------------------------------------------------------------------
		;; Set ptr on var 1st bloc for later updates
		;;-------------------------------------------------------------------------------------------------------------------------------
		ld l,e
		ld h,d
		ld bc,OFS_B1a_FirstSeq		; go to "ptr on first seq"
		add hl,bc
		push hl				; save Ptr on sequence ptr
		;;-------------------------------------------------------------------------------------------------------------------------------
		; Copy 1st bloc (a) of loader in ram
		;;-------------------------------------------------------------------------------------------------------------------------------
		;
		ld hl,Ayt_PLayer_B1a_Start
		ld bc,Ayt_Player_B1a_End-Ayt_Player_B1a_Start
		ldir

		ex de,hl			; ptr on player code
		ld (hl),#11			; "ld de,xxxx", coded
		inc hl
		ld (Ayt_PatternidxPtr),hl
		ld (hl),c			; ld de,0
		inc hl
		ld (hl),c
		inc hl
		ex de,hl			; Cur ptr on player code in DE

		;----------------------------------------------------------------
		; Manage remaining active regs while creating player ay-send block
		;----------------------------------------------------------------
		ld l,(ix+AYT_OFS_ActiveRegs)
		ld h,(ix+AYT_OFS_ActiveRegs+1)	; bit 15, 14, 13, ... of HL are active ay reg 0, 1, 2, 3... if 1
		ld a,#a0			; ay num 1st reg

Ayt_CreateActiveReg
		add hl,hl			; seek active reg
		jr nc,Ayt_NextReg		; reg is inactive 
		ld (Ayt_DavePort),a		; update Cur Dave reg
		push hl				; copy "send ay block" with "inc c"
		ld hl,Ayt_Player_B2_Start	; Create io block for idx reg a
		ld c,AYT_B2_SIZE
		ldir
		pop hl
		cp #a8				; amplitude canal 0 , bit 7=1 >> drive endmusic
		jr c,Ayt_NextReg		; Not a volume
		jr nz,Ayt_NoVolCanal0		; Not channel 0
		ex de,hl
		ld (hl),#b7			; or a >> permet de positionner le sF 
		inc hl
		ex de,hl
Ayt_NoVolCanal0
		if PlayerStereo
			push af
			add a,4
			ex de,hl
			ld (hl),#d3
			inc hl
			ld (hl),a
			inc hl
			ex de,hl
			pop af	
		endif
Ayt_NextReg
		inc a				; next ay reg counter
		cp #ac
		jr nz,Ayt_CreateActiveReg	; 
		;
		; Create Last Part R13 & Loop control
		;
		ld hl,OFS_B3_Ayt_NotLastSeq
		add hl,de
		ld (Ayt_PtrJPEndSeq),hl

		ld hl,Ayt_Player_B3_Start
		ld c,AYT_B3_SIZE
		push de
		push de		
		ldir
		;
		; Link var
		;
		pop bc				; Ptr on struct B3 for calc
		pop iy				; Ptr on struct
		ld hl,OFS_B3_MusicCnt
		add hl,bc			; HL=Abs ptr on MusicCntPtr
		ld (iy+OFS_B3_MusicCntPtr),l
		ld (iy+OFS_B3_MusicCntPtr+1),h
		;
		;
Ayt_PatternidxPtr equ $+1
		ld hl,0				; HL=ptr on pattern idx ptr
		ld (iy+OFS_B3_PatCountPtr1),l
		ld (iy+OFS_B3_PatCountPtr1+1),h
		ld (iy+OFS_B3_PatCountPtr2),l
		ld (iy+OFS_B3_PatCountPtr2+1),h
		pop hl
		ld (iy+OFS_B3_SeqPatPtr_Upd),l	; HL=ptr on sequence ptr 
		ld (iy+OFS_B3_SeqPatPtr_Upd+1),h
		;
	ifnot PlayerAccessByJP				; Player called by call then reload SP
		ld hl,OFS_B3_Ayt_ReloadSP
		add hl,bc
		pop iy				; rec struct B1
		ld (iy+OFS_B1_PtrSaveSP),l
		ld (iy+OFS_B1_PtrSaveSP+1),h
	endif	
		;----------------------------------------------------------------
		; Last block for init routine
		;----------------------------------------------------------------
		ex de,hl
		ld (hl),#c9			; Ret if no ay reg to set
Ayt_InitCreate	equ $+1
		ld a,0				; Ay Reg to init ? (0xFF=Empty list)
		inc a
		ret z				; No (14 register or non available) & give ptr
		ex de,hl
		push de
		ld hl,Ayt_Player_B4_Start
		ld bc,AYT_B4_SIZE		; block 4 created
		ldir		
		pop hl				; Give ptr to user
		ret	
		
;===============================================================================================================================================
; Raw code template used by the builder
;===============================================================================================================================================
;-----------------------------------------------------------------------------------------------------------------------------------------------
Ayt_Player_B1a_Start
	ifnot PlayerAccessByJP
Ayt_PtrSaveSP	equ $+2
		ld (0),sp		; 20 ts SP is saved if player is "called"
	endif		
Ayt_FirstSeq	equ $+1
		ld sp,0
Ayt_Player_B1a_End
;-----------------------------------------------------------------------------------------------------------------------------------------------
Ayt_Player_B2_Start	
		pop hl			; Get Pattern Ptr
		add hl,de		; + offset in Pattern
		ld a,(hl)		; read dave data
Ayt_DavePort	equ $+1
		out (#a0),a 		; Send to dave 
Ayt_Player_B2_End
;-----------------------------------------------------------------------------------------------------------------------------------------------
Ayt_Player_B3_Start
Ayt_PtrJPEndSeq	equ $+1
		jp p,Ayt_NotLastSeq	; 10/10/10/10 
Ayt_MusicCnt equ $+1			; -------------- 
		ld a,0			; 00/07/07/00  Loop counter 
		dec a			; 00/04/04/00  
		jr z,Ayt_MusicEnd	; 00/12/07/00  Loop finished ?
Ayt_MusicCntPtr equ $+1			; 	       Player on mute
		ld (0),a		; 00/00/13/00  Music loops > loop counter upd
Ayt_LoopSeq  equ $+1
		ld sp,0			; 00/00/10/00  Ptr on sequence loop
		jr Ayt_Player_NewSeq	; 00/00/12/00     
		;-------------------------------------
Ayt_MusicEnd		
		ex (sp),hl		; 00/19/00/00 Delay
		ex (sp),hl		; 00/19/00/00 Delay
		add hl,bc		; 00/11/00/00 Delay
		dec hl			; 00/06/00/00 Delay
		jr Ayt_PlayerExit	; 00/12/00/00 Delay
		;-------------------------------------
		;                            
Ayt_NotLastSeq				
Ayt_PatCountPtr1 equ $+1
		ld a,(0)		; 13/00/00/13  Get Pattern offset
		inc a			; 04/00/00/04  Offset +1
Ayt_PatternSize	equ $+1
		cp  0			; 07/00/00/07 Pattern completed ?
		jr z,Ayt_EndPattern	; 12/00/00/07 Delay 
		inc (hl)		; 00/00/00/11 Delay
		dec (hl)		; 00/00/00/11 Delay
		jr $+2			; 00/00/00/12 Delay
		jr Ayt_SeqPat		; 00/00/00/12 Delay
		;-------------------------------------
Ayt_EndPattern				;
		add hl,bc		; 11/00/00/00 Delay
		dec hl			; 06/00/00/00 Delay
Ayt_Player_NewSeq
Ayt_SeqPatternPtr_Upd equ $+2		; !!! Critical here !!!
		ld (0),sp		; 20/00/20/00  Update ptr of seq on patterns
		xor a			; 04/00/04/00  Offset all pattern to 0
Ayt_SeqPat
Ayt_PatCountPtr2 equ $+1		; 
		ld (0),a		; 13/00/13/13  Update offset on patterns 
					; -------------
					; 90/90/90/90 (3rd max)
Ayt_PlayerExit
	if PlayerAccessByJP
Ayt_ExitPtr01	equ $+1
		jp 0 			; exit from player via JP 
	else	
Ayt_ReloadSP	equ $+1
		ld sp,0			; Player was called , SP is restored
		ret			; and return to main code
	endif
Ayt_Player_B3_End
;-----------------------------------------------------------------------------------------------------------------------------------------------
; Init of not active AY reg
; 
Ayt_Player_B4_Start
Ayt_PtrInitList	equ $+1
		ld hl,0
Ayt_InitReg_Loop
		ld c,(hl)		; get register idx		; Attention liste sur #A0,...
		bit 7,c			; End list of init ay reg
		ret nz			; yes
		inc hl			; no ptr on data
		outi			; Send (hl) to ay and hl++
		jr Ayt_InitReg_Loop	; next reg
Ayt_Player_B4_End
;-----------------------------------------------------------------------------------------------------------------------------------------------
Ayt_Builder_End
;;++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
